import { Inter } from 'next/font/google';
import './globals.css';
import ThemeProviderClient from '@/components/providers/ThemeProviderClient';
import { CssBaseline } from '@mui/material';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import NavBar from '@/components/navigation/NavBar';
import SignInBtn from '@/components/navigation/SignInBtn';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProviderClient>
          <CssBaseline />
          <main>
            {children}
            <ToastContainer
              position='top-right'
              autoClose={3000}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              theme='light'
            />
          </main>
        </ThemeProviderClient>
      </body>
    </html>
  );
}
